In [5]:
# Importación de librerías
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/home/tipoweb/radia_dir/00_film/IMDBMovieData-01.csv')
#test de nulos
df.isnull().sum()

Rank                  0
Title                 0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
dtype: int64

In [6]:
# nº de elementos distintos en cada variable
df.nunique()

Rank                  1000
Title                  999
Genre                  207
Description           1000
Director               644
Actors                 996
Year                    11
Runtime (Minutes)       94
Rating                  55
Votes                  997
Revenue (Millions)     814
Metascore               85
dtype: int64

In [7]:
# tipo de dato de cada variable
df.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore               int64
dtype: object

In [8]:
# distintos datos en la variable 'ca'
df['ca'].unique()

array([0, 2, 1, 3, 4])

In [9]:
# contar el nº de registros en cada valor de forma descendente
df.ca.value_counts()

ca
0    175
1     65
2     38
3     20
4      5
Name: count, dtype: int64

In [10]:
# mostra las filas del valor '4'
df[df['ca']==4]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak   
92    52    1   2       138   223    0        1      169      0      0.0  \
158   58    1   1       125   220    0        1      144      0      0.4   
163   38    1   2       138   175    0        1      173      0      0.0   
164   38    1   2       138   175    0        1      173      0      0.0   
251   43    1   0       132   247    1        0      143      1      0.1   

     slope  ca  thal  target  
92       2   4     2       1  
158      1   4     3       1  
163      2   4     2       1  
164      2   4     2       1  
251      1   4     3       0

In [11]:
df.loc[df['ca']==4] = np.NaN

In [12]:
df['ca'].unique()

array([ 0.,  2.,  1.,  3., nan])

In [13]:
# distintos datos en la variable 'thal'
df['thal'].unique()

array([ 1.,  2.,  3.,  0., nan])

In [14]:
# contar el nº de registros en cada valor de forma descendente
df.thal.value_counts()

thal
2.0    163
3.0    115
1.0     18
0.0      2
Name: count, dtype: int64

In [15]:
# mostra las filas del valor '0'
df[df['thal']==0]

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak   
48   53.0  0.0  2.0     128.0  216.0  0.0      0.0    115.0    0.0      0.0  \
281  52.0  1.0  0.0     128.0  204.0  1.0      1.0    156.0    1.0      1.0   

     slope   ca  thal  target  
48     2.0  0.0   0.0     1.0  
281    1.0  0.0   0.0     0.0

In [16]:
df.loc[df['thal']==0] = np.NaN

In [17]:
df['thal'].unique()

array([ 1.,  2.,  3., nan])

In [18]:
#Reemplazar los NaN con la mediana
df = df.fillna(df.median)
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [19]:
# datos estadísticos básicos
estadisticas = df.describe(include='all')
print(estadisticas)

          age    sex     cp  trestbps   
count   303.0  303.0  303.0     303.0  \
unique   42.0    3.0    5.0      50.0   
top      58.0    1.0    0.0     120.0   
freq     18.0  201.0  141.0      37.0   

                                                     chol    fbs  restecg   
count                                                 303  303.0    303.0  \
unique                                                153    3.0      4.0   
top     <bound method NDFrame._add_numeric_operations....    0.0      1.0   
freq                                                    7  253.0    147.0   

        thalach  exang  oldpeak  slope     ca   thal  target  
count     303.0  303.0    303.0  303.0  303.0  303.0   303.0  
unique     92.0    3.0     41.0    4.0    5.0    4.0     3.0  
top       162.0    0.0      0.0    2.0    0.0    2.0     1.0  
freq       11.0  199.0     95.0  138.0  173.0  163.0   160.0  


In [20]:
# veamos las medias
media = df.mean()
print(media)

TypeError: unsupported operand type(s) for +: 'float' and 'method'

In [22]:
duplicados = df.duplicated().sum()
print(duplicados)

AttributeError: 'numpy.int64' object has no attribute 'duplicated'